# Generated by Django 3.0.5 on 2020-04-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commentaires',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
