# Generated by Django 3.0.5 on 2020-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_profile_commentaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
